<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="9" hostname="DESKTOP-A9DN365" name="testNg.TestCases2" tests="11" failures="0" timestamp="03 Jun 2021 03:27:13 GMT" time="13.160" errors="1">
  <testcase name="afterMethod" time="0.012" classname="testNg.TestCases2">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNg.TestCases2.afterMethod(TestCases2.java:621)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterMethod -->
  <testcase name="brokenLinks" time="13.148" classname="testNg.TestCases2"/>
  <testcase name="HandlingAlerts" time="0.000" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- HandlingAlerts -->
  <testcase name="HandlingFrames" time="0.000" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- HandlingFrames -->
  <testcase name="handlingWindows" time="0.000" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- handlingWindows -->
  <testcase name="mouseOperations" time="0.000" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- mouseOperations -->
  <testcase name="FileUpload" time="0.000" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- FileUpload -->
  <testcase name="DataDrivenAutomationDemoSite" time="0.000" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- DataDrivenAutomationDemoSite -->
  <testcase name="verifyExternalFrameBackpackOrder" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- verifyExternalFrameBackpackOrder -->
  <testcase name="verifyEnterGMOOnlineLoadedSuccessfully" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- verifyEnterGMOOnlineLoadedSuccessfully -->
  <testcase name="verifyGmoOnlineLoadedSuccusessfully" classname="testNg.TestCases2">
    <skipped/>
  </testcase> <!-- verifyGmoOnlineLoadedSuccusessfully -->
</testsuite> <!-- testNg.TestCases2 -->
